{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">>> Imports:\n",
      "#coding=utf-8\n",
      "\n",
      "from __future__ import print_function\n",
      "\n",
      "try:\n",
      "    import numpy as np\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from hyperopt import Trials, STATUS_OK, tpe\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from hyperas import optim\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from hyperas.distributions import choice, uniform\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.preprocessing import sequence\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.datasets import imdb\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.models import Sequential\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.layers.core import Dense, Dropout, Activation\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.layers.embeddings import Embedding\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.layers.recurrent import LSTM\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from keras.callbacks import EarlyStopping, ModelCheckpoint\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from pandas import read_csv\n",
      "except:\n",
      "    pass\n",
      "\n",
      "try:\n",
      "    from sklearn.preprocessing import MinMaxScaler\n",
      "except:\n",
      "    pass\n",
      "\n",
      ">>> Hyperas search space:\n",
      "\n",
      "def get_space():\n",
      "    return {\n",
      "        'Dropout': hp.uniform('Dropout', 0, 1),\n",
      "        'batch_size': hp.choice('batch_size', [32, 64, 128]),\n",
      "    }\n",
      "\n",
      ">>> Data\n",
      "  1: \n",
      "  2: \n",
      "  3: maxlen = 352\n",
      "  4: max_features = 6\n",
      "  5: \n",
      "  6: dataset = read_csv('data/test.csv', index_col='Date')\n",
      "  7: X = dataset.drop(labels=['close', 'close_nextday'], axis=1)\n",
      "  8: y = dataset['close_nextday']\n",
      "  9: \n",
      " 10: values_x = X.values\n",
      " 11: values_y = y.values\n",
      " 12: values_y = values_y.reshape(-1, 1)\n",
      " 13: \n",
      " 14: scaler = MinMaxScaler(feature_range=(0, 1))\n",
      " 15: scaled_data_X = scaler.fit_transform(values_x)\n",
      " 16: scaled_data_y = scaler.fit_transform(values_y)\n",
      " 17: \n",
      " 18: X_train = scaled_data_X[:int(X.shape[0] * 0.8)]\n",
      " 19: X_test = scaled_data_X[int(y.shape[0] * 0.8):]\n",
      " 20: y_train = scaled_data_y[:int(X.shape[0] * 0.8)]\n",
      " 21: y_test = scaled_data_y[int(y.shape[0] * 0.8):]\n",
      " 22: \n",
      " 23: X_train = np.array(X_train)\n",
      " 24: X_test = np.array(X_test)\n",
      " 25: print(len(X_train), 'train sequences')\n",
      " 26: print(len(X_test), 'test sequences')\n",
      " 27: \n",
      " 28: print(\"Pad sequences (samples x time)\")\n",
      " 29: y_train = np.array(y_train)\n",
      " 30: y_test = np.array(y_test)\n",
      " 31: print('X_train shape:', X_train.shape)\n",
      " 32: print('X_test shape:', X_test.shape)\n",
      " 33: \n",
      " 34: \n",
      " 35: \n",
      " 36: \n",
      " 37: \n",
      ">>> Resulting replaced keras model:\n",
      "\n",
      "  1: def keras_fmin_fnct(space):\n",
      "  2: \n",
      "  3:     \n",
      "  4:     model = Sequential()\n",
      "  5:     model.add(Embedding(max_features, 128, input_length=maxlen))\n",
      "  6:     model.add(LSTM(128))\n",
      "  7:     model.add(Dropout(space['Dropout']))\n",
      "  8:     model.add(Dense(1))\n",
      "  9:     model.add(Activation('sigmoid'))\n",
      " 10: \n",
      " 11:     model.compile(loss='binary_crossentropy',\n",
      " 12:                   optimizer='adam',\n",
      " 13:                   metrics=['accuracy'])\n",
      " 14: \n",
      " 15:     early_stopping = EarlyStopping(monitor='val_loss', patience=4)\n",
      " 16:     checkpointer = ModelCheckpoint(filepath='keras_weights.hdf5',\n",
      " 17:                                    verbose=1,\n",
      " 18:                                    save_best_only=True)\n",
      " 19: \n",
      " 20:     model.fit(X_train, y_train,\n",
      " 21:               batch_size=space['batch_size'],\n",
      " 22:               epochs=1,\n",
      " 23:               validation_split=0.8,\n",
      " 24:               callbacks=[early_stopping, checkpointer])\n",
      " 25: \n",
      " 26:     score, acc = model.evaluate(X_test, y_test, verbose=0)\n",
      " 27: \n",
      " 28:     print('Test accuracy:', acc)\n",
      " 29:     return {'loss': -acc, 'status': STATUS_OK, 'model': model}\n",
      " 30: \n",
      "352 train sequences\n",
      "89 test sequences\n",
      "Pad sequences (samples x time)\n",
      "X_train shape: (352, 6)\n",
      "X_test shape: (89, 6)\n",
      "  0%|                                                                           | 0/10 [00:00<?, ?trial/s, best loss=?]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_input'), name='embedding_input', description=\"created by layer 'embedding_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_input'), name='embedding_input', description=\"created by layer 'embedding_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "1/1 [==============================]                                                                                   \n",
      " - ETA: 0s - loss: 0.6958 - accuracy: 0.0000e+00                                                                       \n",
      "  0%|                                                                           | 0/10 [00:03<?, ?trial/s, best loss=?]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_input'), name='embedding_input', description=\"created by layer 'embedding_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "1/1 [==============================]                                                                                   \n",
      " - 5s 5s/step - loss: 0.6958 - accuracy: 0.0000e+00 - val_loss: 0.6851 - val_accuracy: 0.0035                          \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.68509, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 10%|██████▎                                                        | 1/10 [00:05<00:51,  5.72s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_1_input'), name='embedding_1_input', description=\"created by layer 'embedding_1_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_1_input'), name='embedding_1_input', description=\"created by layer 'embedding_1_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "1/3 [=========>....................]                                                                                   \n",
      " - ETA: 4s - loss: 0.6915 - accuracy: 0.0000e+00                                                                       \n",
      "                                                                                                                      \n",
      "3/3 [==============================]                                                                                   \n",
      " - ETA: 0s - loss: 0.6884 - accuracy: 0.0000e+00                                                                       \n",
      " 10%|██████▎                                                        | 1/10 [00:08<00:51,  5.72s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_1_input'), name='embedding_1_input', description=\"created by layer 'embedding_1_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "3/3 [==============================]                                                                                   \n",
      " - 3s 336ms/step - loss: 0.6879 - accuracy: 0.0000e+00 - val_loss: 0.6614 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.66135, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.0                                                                                                                    \n",
      " 20%|████████████▌                                                  | 2/10 [00:09<00:40,  5.07s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_2_input'), name='embedding_2_input', description=\"created by layer 'embedding_2_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_2_input'), name='embedding_2_input', description=\"created by layer 'embedding_2_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "1/2 [==============>...............]                                                                                   \n",
      " - ETA: 2s - loss: 0.6938 - accuracy: 0.0000e+00                                                                       \n",
      " 20%|████████████▌                                                  | 2/10 [00:12<00:40,  5.07s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_2_input'), name='embedding_2_input', description=\"created by layer 'embedding_2_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "2/2 [==============================]                                                                                   \n",
      " - 3s 582ms/step - loss: 0.6934 - accuracy: 0.0000e+00 - val_loss: 0.6769 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.67686, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 30%|██████████████████▉                                            | 3/10 [00:12<00:32,  4.61s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_3_input'), name='embedding_3_input', description=\"created by layer 'embedding_3_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_3_input'), name='embedding_3_input', description=\"created by layer 'embedding_3_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "1/2 [==============>...............]                                                                                   \n",
      " - ETA: 2s - loss: 0.6897 - accuracy: 0.0000e+00                                                                       \n",
      " 30%|██████████████████▉                                            | 3/10 [00:15<00:32,  4.61s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_3_input'), name='embedding_3_input', description=\"created by layer 'embedding_3_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "2/2 [==============================]                                                                                   \n",
      " - 3s 586ms/step - loss: 0.6891 - accuracy: 0.0000e+00 - val_loss: 0.6699 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.66988, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 40%|█████████████████████████▏                                     | 4/10 [00:16<00:25,  4.28s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_4_input'), name='embedding_4_input', description=\"created by layer 'embedding_4_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_4_input'), name='embedding_4_input', description=\"created by layer 'embedding_4_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_train_function.<locals>.train_function at 0x000002987CA703A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "1/3 [=========>....................]                                                                                   \n",
      " - ETA: 4s - loss: 0.6873 - accuracy: 0.0000e+00                                                                       \n",
      " 40%|█████████████████████████▏                                     | 4/10 [00:19<00:25,  4.28s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_4_input'), name='embedding_4_input', description=\"created by layer 'embedding_4_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "3/3 [==============================]                                                                                   \n",
      " - 3s 318ms/step - loss: 0.6843 - accuracy: 0.0000e+00 - val_loss: 0.6620 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.66200, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 50%|███████████████████████████████▌                               | 5/10 [00:19<00:20,  4.07s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_5_input'), name='embedding_5_input', description=\"created by layer 'embedding_5_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_5_input'), name='embedding_5_input', description=\"created by layer 'embedding_5_input'\"), but it was called on an input with incompatible shape (None, 6).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x000002987FB349D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "1/1 [==============================]                                                                                   \n",
      " - ETA: 0s - loss: 0.6942 - accuracy: 0.0000e+00                                                                       \n",
      " 50%|███████████████████████████████▌                               | 5/10 [00:22<00:20,  4.07s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_5_input'), name='embedding_5_input', description=\"created by layer 'embedding_5_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "1/1 [==============================]                                                                                   \n",
      " - 3s 3s/step - loss: 0.6942 - accuracy: 0.0000e+00 - val_loss: 0.6830 - val_accuracy: 0.0035                          \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.68302, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 60%|█████████████████████████████████████▊                         | 6/10 [00:23<00:15,  3.81s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_6_input'), name='embedding_6_input', description=\"created by layer 'embedding_6_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_6_input'), name='embedding_6_input', description=\"created by layer 'embedding_6_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_train_function.<locals>.train_function at 0x000002980419C550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "1/3 [=========>....................]                                                                                   \n",
      " - ETA: 5s - loss: 0.6960 - accuracy: 0.0000e+00                                                                       \n",
      " 60%|█████████████████████████████████████▊                         | 6/10 [00:25<00:15,  3.81s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_6_input'), name='embedding_6_input', description=\"created by layer 'embedding_6_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "3/3 [==============================]                                                                                   \n",
      " - 3s 306ms/step - loss: 0.6921 - accuracy: 0.0000e+00 - val_loss: 0.6663 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.66629, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 70%|████████████████████████████████████████████                   | 7/10 [00:26<00:11,  3.76s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_7_input'), name='embedding_7_input', description=\"created by layer 'embedding_7_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_7_input'), name='embedding_7_input', description=\"created by layer 'embedding_7_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_train_function.<locals>.train_function at 0x0000029808343820> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "1/1 [==============================]                                                                                   \n",
      " - ETA: 0s - loss: 0.6917 - accuracy: 0.0000e+00                                                                       \n",
      " 70%|████████████████████████████████████████████                   | 7/10 [00:29<00:11,  3.76s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_7_input'), name='embedding_7_input', description=\"created by layer 'embedding_7_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "1/1 [==============================]                                                                                   \n",
      " - 3s 3s/step - loss: 0.6917 - accuracy: 0.0000e+00 - val_loss: 0.6803 - val_accuracy: 0.0035                          \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.68034, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " 80%|██████████████████████████████████████████████████▍            | 8/10 [00:30<00:07,  3.61s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_8_input'), name='embedding_8_input', description=\"created by layer 'embedding_8_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_8_input'), name='embedding_8_input', description=\"created by layer 'embedding_8_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x0000029808343160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "1/3 [=========>....................]                                                                                   \n",
      " - ETA: 4s - loss: 0.6965 - accuracy: 0.0000e+00                                                                       \n",
      " 80%|██████████████████████████████████████████████████▍            | 8/10 [00:32<00:07,  3.61s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_8_input'), name='embedding_8_input', description=\"created by layer 'embedding_8_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "3/3 [==============================]                                                                                   \n",
      " - 3s 315ms/step - loss: 0.6923 - accuracy: 0.0000e+00 - val_loss: 0.6652 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.66516, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      " 90%|████████████████████████████████████████████████████████▋      | 9/10 [00:33<00:03,  3.64s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_9_input'), name='embedding_9_input', description=\"created by layer 'embedding_9_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_9_input'), name='embedding_9_input', description=\"created by layer 'embedding_9_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_train_function.<locals>.train_function at 0x000002980FE00310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "1/2 [==============>...............]                                                                                   \n",
      " - ETA: 2s - loss: 0.6982 - accuracy: 0.0000e+00                                                                       \n",
      " 90%|████████████████████████████████████████████████████████▋      | 9/10 [00:36<00:03,  3.64s/trial, best loss: -0.0]WARNING:tensorflow:Model was constructed with shape (None, 352) for input KerasTensor(type_spec=TensorSpec(shape=(None, 352), dtype=tf.float32, name='embedding_9_input'), name='embedding_9_input', description=\"created by layer 'embedding_9_input'\"), but it was called on an input with incompatible shape (None, 6).\n",
      "                                                                                                                      \n",
      "2/2 [==============================]                                                                                   \n",
      " - 3s 624ms/step - loss: 0.6977 - accuracy: 0.0000e+00 - val_loss: 0.6779 - val_accuracy: 0.0035                       \n",
      "\n",
      "                                                                                                                       \n",
      "Epoch 00001: val_loss improved from inf to 0.67788, saving model to keras_weights.hdf5\n",
      "Test accuracy:                                                                                                         \n",
      "0.0                                                                                                                    \n",
      "100%|██████████████████████████████████████████████████████████████| 10/10 [00:37<00:00,  3.71s/trial, best loss: -0.0]\n",
      "{'Dropout': 0.21280043312755825, 'batch_size': 2}\n"
     ]
    }
   ],
   "source": [
    "from __future__ import print_function\n",
    "import numpy as np\n",
    "\n",
    "from hyperopt import Trials, STATUS_OK, tpe\n",
    "from hyperas import optim\n",
    "from hyperas.distributions import choice, uniform\n",
    "from keras.preprocessing import sequence\n",
    "from keras.datasets import imdb\n",
    "from keras.models import Sequential\n",
    "from keras.layers.core import Dense, Dropout, Activation\n",
    "from keras.layers.embeddings import Embedding\n",
    "from keras.layers.recurrent import LSTM\n",
    "from keras.callbacks import EarlyStopping, ModelCheckpoint\n",
    "\n",
    "\n",
    "from pandas import read_csv\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "\n",
    "\n",
    "\n",
    "def data():\n",
    "    \n",
    "    maxlen = 352\n",
    "    max_features = 6\n",
    "    \n",
    "    dataset = read_csv('data/test.csv', index_col='Date')\n",
    "    X = dataset.drop(labels=['close', 'close_nextday'], axis=1)\n",
    "    y = dataset['close_nextday']\n",
    "\n",
    "    values_x = X.values\n",
    "    values_y = y.values\n",
    "    values_y = values_y.reshape(-1, 1)\n",
    "\n",
    "    scaler = MinMaxScaler(feature_range=(0, 1))\n",
    "    scaled_data_X = scaler.fit_transform(values_x)\n",
    "    scaled_data_y = scaler.fit_transform(values_y)\n",
    "\n",
    "    X_train = scaled_data_X[:int(X.shape[0] * 0.8)]\n",
    "    X_test = scaled_data_X[int(y.shape[0] * 0.8):]\n",
    "    y_train = scaled_data_y[:int(X.shape[0] * 0.8)]\n",
    "    y_test = scaled_data_y[int(y.shape[0] * 0.8):]\n",
    "\n",
    "    X_train = np.array(X_train)\n",
    "    X_test = np.array(X_test)\n",
    "    print(len(X_train), 'train sequences')\n",
    "    print(len(X_test), 'test sequences')\n",
    "    \n",
    "    print(\"Pad sequences (samples x time)\")\n",
    "    y_train = np.array(y_train)\n",
    "    y_test = np.array(y_test)\n",
    "    print('X_train shape:', X_train.shape)\n",
    "    print('X_test shape:', X_test.shape)\n",
    "    \n",
    "\n",
    "    return X_train, X_test, y_train, y_test, max_features, maxlen\n",
    "\n",
    "def model(X_train, X_test, y_train, y_test, max_features, maxlen):\n",
    "    \n",
    "    model = Sequential()\n",
    "    model.add(Embedding(max_features, 128, input_length=maxlen))\n",
    "    model.add(LSTM(128))\n",
    "    model.add(Dropout({{uniform(0, 1)}}))\n",
    "    model.add(Dense(1))\n",
    "    model.add(Activation('sigmoid'))\n",
    "\n",
    "    model.compile(loss='binary_crossentropy',\n",
    "                  optimizer='adam',\n",
    "                  metrics=['accuracy'])\n",
    "\n",
    "    early_stopping = EarlyStopping(monitor='val_loss', patience=4)\n",
    "    checkpointer = ModelCheckpoint(filepath='keras_weights.hdf5',\n",
    "                                   verbose=1,\n",
    "                                   save_best_only=True)\n",
    "\n",
    "    model.fit(X_train, y_train,\n",
    "              batch_size={{choice([32, 64, 128])}},\n",
    "              epochs=1,\n",
    "              validation_split=0.8,\n",
    "              callbacks=[early_stopping, checkpointer])\n",
    "\n",
    "    score, acc = model.evaluate(X_test, y_test, verbose=0)\n",
    "\n",
    "    print('Test accuracy:', acc)\n",
    "    return {'loss': -acc, 'status': STATUS_OK, 'model': model}\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    best_run, best_model = optim.minimize(model=model,\n",
    "                                          data=data,\n",
    "                                          algo=tpe.suggest,\n",
    "                                          max_evals=10,\n",
    "                                          trials=Trials(),\n",
    "                                          notebook_name='Untitled2')\n",
    "print(best_run)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "latex_envs": {
   "LaTeX_envs_menu_present": true,
   "autoclose": false,
   "autocomplete": true,
   "bibliofile": "biblio.bib",
   "cite_by": "apalike",
   "current_citInitial": 1,
   "eqLabelWithNumbers": true,
   "eqNumInitial": 1,
   "hotkeys": {
    "equation": "Ctrl-E",
    "itemize": "Ctrl-I"
   },
   "labels_anchors": false,
   "latex_user_defs": false,
   "report_style_numbering": false,
   "user_envs_cfg": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
